@SET SCOUTER_JAVA_AGENT_CONF=scouter\conf\board-webapp.conf
@SET SCOUTER_JAVA_AGENT_LIB=C:\scouter\scouter\agent.java\scouter.agent.jar
@SET LATEST_PROJECT_HOME=part07\jex06-board
@echo SCOUTER_JAVA_AGENT_CONF=%SCOUTER_JAVA_AGENT_CONF%
@echo SCOUTER_JAVA_AGENT_LIB=%SCOUTER_JAVA_AGENT_LIB%
@echo LATEST_PROJECT_HOME=%LATEST_PROJECT_HOME%