version: "0.2"
ignorePaths:
  - .gitignore
dictionaryDefinitions: []
dictionaries: []
words:
  - classloaders
  - Dskip
  - errorlevel
  - FREEPDB
  - Gson
  - gvenzl
  - healthcheck
  - hikari
  - initdb
  - Jstl
  - oradata
  - regdate
  - replyer
  - rttr
  - SETLOCAL
  - Smails
  - temurin
  - Thumbnailator
  - webapps
ignoreWords: []
import: []
