version: "0.2"
ignorePaths:
  - .gitignore
dictionaryDefinitions: []
dictionaries: []
words:
  - classloaders
  - FREEPDB
  - Gson
  - gvenzl
  - healthcheck
  - hikari
  - initdb
  - Jstl
  - oradata
  - regdate
  - replyer
  - rttr
  - Smails
  - Thumbnailator
ignoreWords: []
import: []
