services:
  oracle-free:
    image: gvenzl/oracle-free:23-slim
    container_name: my-board-mds-oracle_free_23c
    environment:
      ORACLE_PASSWORD: sys_ex
      APP_USER: book_ex
      APP_USER_PASSWORD: book_ex
      TZ: Asia/Seoul
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./docker/init-scripts:/container-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
      start_interval: 5s

volumes:
  oracle-data:
