# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Build Test

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17-21
      id: setup-java-17-21
      uses: actions/setup-java@v4
      with:                
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        mvn-toolchain-vendor: Eclipse Temurin
        java-version: |
          17
          21
        mvn-toolchain-id: |
          17
          21

    - name: Build with Maven (my-board-spring5 test)
      run: mvn -B clean test --file part-last/my-board-spring5/pom.xml -t toolchains.xml

    - name: Build with Maven (my-board test (jakarta))
      run: mvn -B clean test --file part-last/my-board/pom.xml -t toolchains.xml

#    - name: Publish to GitHub Packages Apache Maven
#      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
#      env:
#        GITHUB_TOKEN: ${{ github.token }}
